force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Game ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Player_1__c.field-meta.xml
<CustomField>
    <fullName>Player_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player 1</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Games as Player 1</relationshipLabel>
    <relationshipName>Games_as_Player_1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Player_2__c.field-meta.xml
<CustomField>
    <fullName>Player_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player 2</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Games as Player 2</relationshipLabel>
    <relationshipName>Games_as_Player_2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/WNHC_Game_Id__c.field-meta.xml
<CustomField>
    <fullName>WNHC_Game_Id__c</fullName>
    <externalId>true</externalId>
    <label>WNHC Game Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/VFController.cls
public class VFController {
	
    private final Game__c game;
    public VFController(ApexPages.StandardController stdController) {
        this.game = (Game__c) stdController.getRecord();
    }
    
    public PageReference autoRun() {
 
        String theId = ApexPages.currentPage().getParameters().get('id');
 
        if (theId == null) {
            // Display the Visualforce page's content if no Id is passed over
            return null;
        }
 
        for(Game__c g : [SELECT Id, Player_1__c, Player_2__c, WNHC_Game_Id__c FROM Game__c WHERE Id =: theId LIMIT 1]) {
         	List<Game__c> games = new List<Game__c>();
			games.add(g);
			APIHelper.updateGamesFromAPI(games);   
        }
 
        // Redirect the user back to the original page
        PageReference pageRef = new PageReference('/' + theId);
        pageRef.setRedirect(true);
        return pageRef;
    }
}