force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Game ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Loser__c.field-meta.xml
<CustomField>
    <fullName>Loser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loser</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Games Lost</relationshipLabel>
    <relationshipName>Games_Lost</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Player_1__c.field-meta.xml
<CustomField>
    <fullName>Player_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player 1</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Games as Player 1</relationshipLabel>
    <relationshipName>Games_as_Player_1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Player_1_Score__c.field-meta.xml
<CustomField>
    <fullName>Player_1_Score__c</fullName>
    <label>Player 1 Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Player_2__c.field-meta.xml
<CustomField>
    <fullName>Player_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player 2</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Games as Player 2</relationshipLabel>
    <relationshipName>Games_as_Player_2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Player_2_Score__c.field-meta.xml
<CustomField>
    <fullName>Player_2_Score__c</fullName>
    <label>Player 2 Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Games</relationshipLabel>
    <relationshipName>Games</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Games Won</relationshipLabel>
    <relationshipName>Games_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Standing__c/Standing__c.object-meta.xml
<CustomObject>
    <label>Standing</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Standing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Standing__c/fields/GA__c.field-meta.xml
<CustomField>
    <fullName>GA__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GA</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/GF__c.field-meta.xml
<CustomField>
    <fullName>GF__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GF</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/GP__c.field-meta.xml
<CustomField>
    <fullName>GP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GP</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/L__c.field-meta.xml
<CustomField>
    <fullName>L__c</fullName>
    <defaultValue>0</defaultValue>
    <label>L</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Standings</relationshipLabel>
    <relationshipName>Standings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Standings</relationshipLabel>
    <relationshipName>Standings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/W__c.field-meta.xml
<CustomField>
    <fullName>W__c</fullName>
    <defaultValue>0</defaultValue>
    <label>W</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tournament ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StandingsHelper.cls
public class StandingsHelper {
    
    @InvocableMethod(label='Update Standings' description='Updates standings for a tournament.')
    public static void updateStandings(List<Tournament__c> tournaments) {
        
        Set<Id> tournamentIds = (new Map<Id,Tournament__c>(tournaments)).keySet();
        
        List<Standing__c> standings;
        List<Game__c> games;
        
        try {
        	standings = [
				SELECT
					Tournament__c,
					Participant__c,
					GP__c,
					W__c,
					L__c,
					GF__c,
					GA__c
	            FROM Standing__c
				WHERE Tournament__c IN : tournamentIds
	        ];
        } catch (QueryException ex) {
        	throw new WNHC_Query_Exception(tournamentIds, 'StandingsHelper.apxc');
    	}
        
        try {
        	games = [
				SELECT
					Player_1__c,
					Player_1_Score__c,
					Player_2__c,
					Player_2_Score__c,
					Winner__c,
					Loser__c,
	            	Tournament__c
				FROM Game__c  
	            WHERE Tournament__c IN : tournamentIds
	        ];
        } catch (QueryException ex) {
        	throw new WNHC_Query_Exception(tournamentIds, 'StandingsHelper.apxc');
    	}
        
		for(Standing__c standing : standings) {
            
			Integer gp = 0;
			Integer w = 0;
			Integer l = 0;
			Integer gf = 0;
			Integer ga = 0;
            
			for(Game__c game : games) {
				if(game.Tournament__c != standing.Tournament__c) continue;  
                if(game.Winner__c == standing.Participant__c) {
                    // a game won by the participant
                    gp++;
                    w++;
                    if(game.Player_1__c == standing.Participant__c) {
						gf += game.Player_1_Score__c.intValue(); // ? not sure why Player_1_Score__c is a Decimal ?
						ga += game.Player_2_Score__c.intValue();                        
					} else {
						ga += game.Player_1_Score__c.intValue();
						gf += game.Player_2_Score__c.intValue();
					}
                }
				if(game.Loser__c == standing.Participant__c) {
					// a game lost by the participant 
					gp++;
                    l++;
                    if(game.Player_1__c == standing.Participant__c) {
						gf += game.Player_1_Score__c.intValue(); // ? not sure why Player_1_Score__c is a Decimal ?
						ga += game.Player_2_Score__c.intValue();                        
					} else {
						ga += game.Player_1_Score__c.intValue();
						gf += game.Player_2_Score__c.intValue();
					}
                }
            }
            
            standing.GP__c = gp;
            standing.W__c = w;
            standing.L__c = l;
            standing.GF__c = gf;
            standing.GA__c = ga;
        }
		
        try {
        	update standings;
        } catch (DMLException ex) {
        	throw new WNHC_DML_Exception(standings, 'StandingsHelper.apxc');
    	}
    }

}