force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Game ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Clock_Minute__c.field-meta.xml
<CustomField>
    <fullName>Clock_Minute__c</fullName>
    <label>Clock Minute</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Clock_Second__c.field-meta.xml
<CustomField>
    <fullName>Clock_Second__c</fullName>
    <label>Clock Second</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Player_1__c.field-meta.xml
<CustomField>
    <fullName>Player_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player 1</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Games as Player 1</relationshipLabel>
    <relationshipName>Games_as_Player_1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Player_1_Score__c.field-meta.xml
<CustomField>
    <fullName>Player_1_Score__c</fullName>
    <label>Player 1 Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Player_2__c.field-meta.xml
<CustomField>
    <fullName>Player_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player 2</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Games as Player 2</relationshipLabel>
    <relationshipName>Games_as_Player_2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Player_2_Score__c.field-meta.xml
<CustomField>
    <fullName>Player_2_Score__c</fullName>
    <label>Player 2 Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Games</relationshipLabel>
    <relationshipName>Games</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Goal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Clock_Minute__c.field-meta.xml
<CustomField>
    <fullName>Clock_Minute__c</fullName>
    <label>Clock Minute</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Clock_Second__c.field-meta.xml
<CustomField>
    <fullName>Clock_Second__c</fullName>
    <label>Clock Second</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Scorer__c.field-meta.xml
<CustomField>
    <fullName>Scorer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Scorer</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Standing__c/Standing__c.object-meta.xml
<CustomObject>
    <label>Standing</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Standing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Standing__c/fields/GA__c.field-meta.xml
<CustomField>
    <fullName>GA__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GA</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/GF__c.field-meta.xml
<CustomField>
    <fullName>GF__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GF</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/GP__c.field-meta.xml
<CustomField>
    <fullName>GP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GP</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/L__c.field-meta.xml
<CustomField>
    <fullName>L__c</fullName>
    <defaultValue>0</defaultValue>
    <label>L</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Standings</relationshipLabel>
    <relationshipName>Standings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/PTS__c.field-meta.xml
<CustomField>
    <fullName>PTS__c</fullName>
    <formula>W__c * 2</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PTS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Standings</relationshipLabel>
    <relationshipName>Standings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Standing__c/fields/W__c.field-meta.xml
<CustomField>
    <fullName>W__c</fullName>
    <defaultValue>0</defaultValue>
    <label>W</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tournament ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StandingTest.cls
@isTest public class StandingTest {
    
    @testSetup static void setup() {
        TestDataFactory.initialize();
    }
    
    @isTest static void testUpdateStandingsAfterGame() {
        
        // A test to ensure GP, W, L, GF, GA etc in Standing__c object gets updated when Game__c object gets status changed to "Completed"
        // or status changed BACK to "In Progress" or "Scheduled".
        
        // select the game from the Test Data Factory and place the game "In Progress"
        Game__c game = [SELECT Id, Tournament__c, Status__c, Player_1__c, Player_1_Score__c, Player_2__c, Player_2_Score__c FROM Game__c LIMIT 1];
        game.Status__c = 'In Progress';
        update game;
        
        // add goals to make the game 2-1
        List<Goal__c> goals = new List<Goal__c>{};
        Goal__c goal1 = new Goal__c(Game__c = game.Id, Scorer__c = game.Player_1__c, Period__c = 1, Clock_Minute__c = 6, Clock_Second__c = 30);
        Goal__c goal2 = new Goal__c(Game__c = game.Id, Scorer__c = game.Player_2__c, Period__c = 2, Clock_Minute__c = 6, Clock_Second__c = 30);
        Goal__c goal3 = new Goal__c(Game__c = game.Id, Scorer__c = game.Player_2__c, Period__c = 3, Clock_Minute__c = 6, Clock_Second__c = 30);
        goals.add(goal1);
        goals.add(goal2);
        goals.add(goal3);
        insert goals;
        
        // complete game, triggering standings update:
        game.Status__c = 'Completed';
        update game;
        
        List<Standing__c> standings = [SELECT Id, Participant__c, GP__c, W__c, L__c, GF__c, GA__c, PTS__c FROM Standing__c WHERE Tournament__c =: game.Tournament__c ORDER BY PTS__c DESC];
        System.assert(standings[0].PTS__c == 2); // make sure P2 winner gets PTS added
        System.assert(standings[0].W__c == 1); // make sure P2 winner gets W added
        System.assert(standings[0].GF__c == 2); // make sure P2 winner gets 2 GF added
        System.assert(standings[0].GA__c == 1); // make sure P2 winner gets 1 GA against
        System.assert(standings[1].PTS__c == 0); // make sure P1 loser gets 0 PTS
        System.assert(standings[1].L__c == 1); // make sure P1 loser gets L added
        System.assert(standings[1].GF__c == 1); // make sure P1 loser gets 1 GF added
        System.assert(standings[1].GA__c == 2); // make sure P1 loser gets 2 GA added
        
        System.assert(standings[0].Participant__c == game.Player_2__c); // ensure P2 winner ends up on top of standings
        System.assert(standings[1].Participant__c == game.Player_1__c); // ensure P1 loser ends up on bottom
        
        // make sure standings "undone" after game status changed away from "Completed":
        game.Status__c = 'In Progress';
        update game;
		standings = [SELECT Id, Participant__c, GP__c, W__c, L__c, GF__c, GA__c, PTS__c FROM Standing__c WHERE Tournament__c =: game.Tournament__c ORDER BY PTS__c DESC];        
        System.assert(standings[0].PTS__c == 0); 
    }

}